--SQL AULA 25 - TIPOS DE DADOS + DESAFIO

---1 BOLEANOS
---2 CARACTERE
---3 NUMEROS
----4 TEMPORAIS

--1 BOELANOS , POR PADRAO ELE É INICIADO COM NULO E PODE RECEBER TANTO 1OU 0 BIT
--2 CARACTERES TAMANHO PERMITE INSETIR UMA QTD FIXA DE CARACTERES E SEMORE OCUPA ESPAÇO RESERVADO 10/50 TAMANHOS VARIAVEIS - VARCHAR OUNVARCHAR , PERMITE INSERIR A QUANTIDADE QUE FOR DEFINIDA, POREM SI USA O ESPAÇO QUE FOR PREENCHIDO

---3 NUMEROS - VALORES EXATOS 
--1 TINYINT NAO TEM PARTE DO VALOR FRACIONADO 1.43,24.23
--2 SMALLINT MESMA COISA POREM LIMITE MAIOR
--3INT MESMA COISA POREM LIMITE MAIOR
---4 BIGINT 
---5 NUMERIC OU DECIMAL - VALORES EXATOS, POREM PERMITE QUE PARTE SEJA FRACIONADO, QUE TAMBÉM OIDE SER ESPECIFICADO E PRECISAO E ESCALA EX :5,2

###VALORES APROXIMADOS
--1 REAL TEM PRECISAO APROXIMADA DE ATÉ 15 DIGITOS
--2 FLOAT - MESMO CONCEITO DO REAL

###VALORES TEMPORAIS
--DATE - ARMAZENA A DATA NO FORMATO AAAA/MM/DD
---DATETIME - ARMAZENA DATA E HORAS AAAA/MM/DD:HH:MM:SS
--DATETIME2 - MESMO DE CIMA POREM COM MILISEGUNDOS
---SMALLDATETIME - DATA E HORA RESPEIRANDO 1900-01-01:00:00:00 ATÉ 2079-06-06:23:59:59
---TIME HORAS MINUTOS E SEFUNDOS RESPEITANDO 00:00:00.000000 TO 23:59:59.9999999
--DATETIMEOFFSET -  PERMITE ARMAZENAR INFO DE DATA E HORAS INCLUINDO O FUSO HORARIO


---