---SQL AULA 24 - SELF JOIN

SELECT A.contactName, a.REGION, B.ContactName, B.REGION
FROM CUSTOMERS A, CUSTOMERS B
WHERE A.REGION = B. REGION

--QUERO O NOME E DATA DE CONTRATAÇÃO ED TODOS OS FUNCIONARIOS QUE FORAM CONTRATADOS NO MESMO ANO

SELECT A.FIRSTNAME , A.hiredate , b.firstname , b.hiredate
FROM EMPLOYEES a, employees b
WHERE DATEPART (YEAR , A.HIREDATE) = DATEPART (YEAR, B.HIREDATE)

SELECT *
FROM Employees

--DESAFIO 
--QUERO SABER NA TABELA DETALHE DO PEDIDO ORDER DETAILS QUAIS PRODUTOS TEM O MESMO % DE DESCONTO

SELECT A.PRODUCTID , A.DISCOUNT , B.PRODUCTID, B.DISCOUNT
FROM [Order Details] A, [Order Details] B
WHERE A.Discount = B.Discount